package com.ginspi.energyintelligence;

public final class ScenarioEngine {
    private ScenarioEngine() {}
    public static double clamp(double v,double min,double max){return Math.max(min,Math.min(max,v));}
    public static ScenarioInput sanitize(ScenarioInput i){return new ScenarioInput(i.country,clamp(i.gas,-50,100),clamp(i.demand,-20,30),clamp(i.wind,-50,50),clamp(i.solar,-50,50),clamp(i.temp,-10,10),clamp(i.imports,-50,50),clamp(i.geo,0,100));}
    public static ScenarioResult evaluate(ScenarioInput raw){ScenarioInput i=sanitize(raw); CountryProfile p=CountryProfiles.forCountry(i.country); double gasPressure=0.42*i.gas*p.gasSensitivity; double demandPressure=0.55*i.demand; double windRelief=-0.20*i.wind; double solarRelief=-0.14*i.solar; double tempPressure=-0.35*i.temp*p.tempSensitivity; double importRelief=-0.18*i.imports; double geoPressure=0.22*i.geo; double priceImpact=gasPressure+demandPressure+windRelief+solarRelief+tempPressure+importRelief+geoPressure; double demandImpact=i.demand+(-0.12*i.temp)+(0.04*i.geo/10.0); double ren=clamp(p.renewables+(0.30*i.wind)+(0.22*i.solar),0,100); double stress=clamp(25+Math.abs(priceImpact)*0.8+Math.max(0,i.gas)*0.20+i.geo*0.35-i.imports*0.15,0,100); double risk=clamp(0.4*stress+0.25*Math.abs(priceImpact)+0.2*p.baseRisk+0.15*i.geo,0,100); return new ScenarioResult(round1(priceImpact),round1(demandImpact),round1(risk),round1(ren),round1(stress));}
    private static double round1(double v){return Math.round(v*10.0)/10.0;}
    public static final class ScenarioInput{public final String country; public final double gas,demand,wind,solar,temp,imports,geo; public ScenarioInput(String country,double gas,double demand,double wind,double solar,double temp,double imports,double geo){this.country=country;this.gas=gas;this.demand=demand;this.wind=wind;this.solar=solar;this.temp=temp;this.imports=imports;this.geo=geo;}}
    public static final class ScenarioResult{public final double priceImpactPct,demandImpactPct,riskScore,renewablesContributionPct,marketStressLevel; public ScenarioResult(double p,double d,double r,double ren,double s){this.priceImpactPct=p;this.demandImpactPct=d;this.riskScore=r;this.renewablesContributionPct=ren;this.marketStressLevel=s;}}
    private static final class CountryProfile{final double gasSensitivity,tempSensitivity,renewables,baseRisk; CountryProfile(double g,double t,double r,double b){gasSensitivity=g;tempSensitivity=t;renewables=r;baseRisk=b;}}
    private static final class CountryProfiles{static CountryProfile forCountry(String c){if(c==null)return def(); switch(c){case"Greece":return new CountryProfile(1.15,0.90,39,58);case"Germany":return new CountryProfile(1.00,0.78,56,42);case"France":return new CountryProfile(0.72,0.62,54,30);case"Italy":return new CountryProfile(1.08,0.84,41,49);case"Spain":return new CountryProfile(0.88,0.74,58,35);case"Netherlands":return new CountryProfile(0.95,0.70,46,38);case"Belgium":return new CountryProfile(0.92,0.68,49,36);case"Austria":return new CountryProfile(0.74,0.60,67,24);case"Portugal":return new CountryProfile(0.83,0.73,63,28);case"Poland":return new CountryProfile(1.18,0.80,33,61);default:return def();}} static CountryProfile def(){return new CountryProfile(1.0,0.7,45,40);}}
}
